#!/usr/bin/env node
/**
 * First-run setup for non-developers.
 *
 *   npm run setup
 *
 * Creates `.env.local` if missing, generates a strong SESSION_PASSWORD, and
 * makes sure the SQLite data/ folder exists. Safe to re-run — it will never
 * overwrite an existing .env.local.
 */
import { randomBytes } from 'node:crypto'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const ROOT = process.cwd()
const ENV_PATH = resolve(ROOT, '.env.local')
const DATA_DIR = resolve(ROOT, 'data')

function hex(bytes) {
  return randomBytes(bytes).toString('hex')
}

if (!existsSync(DATA_DIR)) {
  mkdirSync(DATA_DIR, { recursive: true })
  console.log('· Created data/ directory for SQLite.')
}

if (existsSync(ENV_PATH)) {
  console.log('· .env.local already exists — leaving it alone.')
  console.log('  If you want fresh secrets, delete it and run `npm run setup` again.')
  process.exit(0)
}

const sessionPassword = hex(32) // 64 hex chars, well above the 32-char minimum.

// Human-friendly phrase gating /admin-register — printed below so the person
// running setup is the only one who can bootstrap the admin.
const WORDS = ['espresso', 'cortado', 'latte', 'mocha', 'ristretto', 'lungo', 'macchiato', 'affogato', 'arabica', 'robusta', 'crema', 'portafilter']
const pick = () => WORDS[randomBytes(1)[0] % WORDS.length]
const setupPhrase = `${pick()}-${pick()}-${hex(2)}`

const env = `# Generated by \`npm run setup\` — edit as needed.
# You can re-run setup any time by deleting this file.

# Database (libSQL / SQLite). Two supported forms:
#   • Local file:  file:./data/app.db   ← default, works everywhere
#   • Turso:       libsql://<name>.turso.io   + DATABASE_AUTH_TOKEN below
DATABASE_URL=file:./data/app.db
# DATABASE_AUTH_TOKEN=   # uncomment and set when using Turso

# Encrypts your admin session cookie. Keep it secret, keep it safe.
SESSION_PASSWORD=${sessionPassword}

# Public URL of your app (used for absolute links in emails).
NEXT_PUBLIC_APP_URL=http://localhost:3000

# Required to create the first admin at /admin-register. Delete to disable.
ADMIN_SETUP_PHRASE=${setupPhrase}
`

writeFileSync(ENV_PATH, env, { mode: 0o600 })

console.log('')
console.log('  ✓ Created .env.local')
console.log('')
console.log('  Next:')
console.log('     npm run db:push   # create the database tables')
console.log('     npm run dev       # start the app')
console.log('')
console.log('  Create the first admin at /admin-register with this setup phrase:')
console.log('')
console.log(`     ${setupPhrase}`)
console.log('')
