import Link from 'next/link'
import { ArrowLeft, Rocket } from 'lucide-react'
import { PublicShell } from '@/components/public/shell'

export const metadata = {
  title: 'Deploy — Cafe Cursor',
  description: 'Ship Cafe Cursor on Railway, Vercel + Turso, Fly.io, or self-hosted.',
}

export default function DeployGuidePage() {
  return (
    <PublicShell
      title="Deploy Cafe Cursor"
      tagline="Four ways to get this online. Pick the one that matches your budget and tolerance for config."
    >
      <article className="w-full max-w-none text-[15px] leading-relaxed space-y-10">
        <section className="rounded-[14px] border border-border bg-card p-6 shadow-[0_24px_48px_-12px_rgb(0_0_0_/_0.18),0_8px_16px_-8px_rgb(0_0_0_/_0.12)] dark:shadow-[0_32px_64px_-16px_rgb(0_0_0_/_0.5),0_12px_20px_-8px_rgb(0_0_0_/_0.35)] space-y-4">
          <div className="flex items-center gap-2 text-muted-foreground text-xs uppercase tracking-[0.18em]">
            <Rocket className="size-3.5" /> What you need
          </div>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>Somewhere to run Node 20+ (any of the hosts below works).</li>
            <li>A SQLite-compatible database — a local file, or hosted libSQL (Turso).</li>
            <li>A 32+ char <code className="font-code">SESSION_PASSWORD</code> (generated by <code className="font-code">npm run setup</code>).</li>
          </ul>
        </section>

        <section className="space-y-5">
          <h2 className="font-display text-2xl tracking-tight">1. Railway · recommended for non-devs</h2>
          <p>
            Click, paste secrets, deploy. Railway mounts a persistent volume at{' '}
            <code className="font-code">/data</code> for SQLite.
          </p>
          <ol className="list-decimal pl-5 space-y-2">
            <li>
              Use the{' '}
              <a href="https://railway.app/new" target="_blank" rel="noopener noreferrer" className="underline underline-offset-4">
                Railway &ldquo;New Project&rdquo;
              </a>
              {' '}flow and connect this repo.
            </li>
            <li>
              <strong>Settings → Volumes → New Volume</strong>, mount at{' '}
              <code className="font-code">/data</code> (1 GB is plenty).
            </li>
            <li>
              <strong>Variables</strong>:
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li><code className="font-code">DATABASE_URL=file:/data/app.db</code></li>
                <li><code className="font-code">SESSION_PASSWORD</code> — click &ldquo;Generate&rdquo;.</li>
                <li><code className="font-code">NEXT_PUBLIC_APP_URL</code> — your Railway public URL.</li>
              </ul>
            </li>
            <li>Deploy. The first boot runs <code className="font-code">npm run db:push</code> to create the tables.</li>
            <li>Open the site; it redirects to <code className="font-code">/admin-register</code> for the first admin.</li>
          </ol>
          <p className="text-muted-foreground text-sm">Cost: free tier fits small meetups. ~$5/mo under real load.</p>
        </section>

        <section className="space-y-5">
          <h2 className="font-display text-2xl tracking-tight">2. Vercel + Turso · serverless</h2>
          <p>
            Vercel&apos;s filesystem is ephemeral, so pair it with{' '}
            <a href="https://turso.tech" target="_blank" rel="noopener noreferrer" className="underline underline-offset-4">Turso</a> —
            hosted libSQL with a big free tier. No code changes needed.
          </p>
          <ol className="list-decimal pl-5 space-y-2">
            <li>
              Install the Turso CLI and create a DB:
              <pre className="mt-2 bg-muted rounded-[10px] px-4 py-3 overflow-x-auto font-code text-[13px] leading-relaxed">{`brew install tursodatabase/tap/turso
turso auth login
turso db create cafe-cursor
turso db show cafe-cursor --url        # libsql://...
turso db tokens create cafe-cursor      # eyJ...`}</pre>
            </li>
            <li>
              Deploy this repo to Vercel with env vars:
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li><code className="font-code">DATABASE_URL=libsql://...</code></li>
                <li><code className="font-code">DATABASE_AUTH_TOKEN=eyJ...</code></li>
                <li><code className="font-code">SESSION_PASSWORD</code> — 32+ chars.</li>
                <li><code className="font-code">NEXT_PUBLIC_APP_URL</code> — your Vercel URL.</li>
              </ul>
            </li>
            <li>
              Apply the schema once from your laptop:
              <pre className="mt-2 bg-muted rounded-[10px] px-4 py-3 overflow-x-auto font-code text-[13px] leading-relaxed">{`DATABASE_URL=libsql://... \\
DATABASE_AUTH_TOKEN=eyJ... \\
  npm run db:push`}</pre>
            </li>
          </ol>
          <p className="text-muted-foreground text-sm">
            Turso free tier: 500 databases, 9 GB total, 1 B row reads/mo. Plenty.
          </p>
        </section>

        <section className="space-y-5">
          <h2 className="font-display text-2xl tracking-tight">3. Fly.io · SQLite + Litestream</h2>
          <p>
            For when you want local SQLite backed up continuously to S3.
            Overkill for a meetup, but bulletproof.
          </p>
          <pre className="bg-muted rounded-[10px] px-4 py-3 overflow-x-auto font-code text-[13px] leading-relaxed">{`fly launch
fly volumes create data --size 1
fly secrets set \\
  DATABASE_URL=file:/data/app.db \\
  SESSION_PASSWORD=$(openssl rand -hex 32) \\
  NEXT_PUBLIC_APP_URL=https://your-app.fly.dev
fly deploy`}</pre>
        </section>

        <section className="space-y-5">
          <h2 className="font-display text-2xl tracking-tight">4. Self-hosted · Docker, VPS, anywhere</h2>
          <p>
            Anywhere that runs Node 20+. Clone, install, run.
          </p>
          <pre className="bg-muted rounded-[10px] px-4 py-3 overflow-x-auto font-code text-[13px] leading-relaxed">{`git clone https://github.com/ricgarcas/cafe-cursor-credits
cd cafe-cursor-credits
npm run init      # generates .env.local + SESSION_PASSWORD, creates data/
npm run build
npm run start`}</pre>
          <p className="text-muted-foreground text-sm">
            Front it with Caddy / Nginx and point a domain at it. Set
            <code className="font-code">NEXT_PUBLIC_APP_URL</code> to the public
            URL so email links resolve.
          </p>
        </section>

        <section className="space-y-5">
          <h2 className="font-display text-2xl tracking-tight">After deploy</h2>
          <ol className="list-decimal pl-5 space-y-2">
            <li>Open the site — any URL redirects to <code className="font-code">/admin-register</code> until the first admin is created.</li>
            <li>Create the admin, complete onboarding.</li>
            <li>Add coupon codes in bulk via <strong>Codes → Bulk add</strong>.</li>
            <li>Wire email: <Link href="/docs/resend" className="underline underline-offset-4">Resend</Link> or <Link href="/docs/gmail" className="underline underline-offset-4">Gmail SMTP</Link>.</li>
          </ol>
        </section>

        <div className="pt-4">
          <Link
            href="/admin/dashboard"
            className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"
          >
            <ArrowLeft className="size-4" /> Back to dashboard
          </Link>
        </div>
      </article>
    </PublicShell>
  )
}
